version: '3.8'

services:
  db:
    image: postgres:16
    container_name: protein_postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: protein-backend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: protein-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres-data:

#docker-compose up --build
#Frontend: http://localhost:3000
#Backend API: http://localhost:8000/api
